import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientSessionProvider from "./components/ClientSessionProvider";
import { TranslationProvider } from "./context/TranslationProvider";
import NavbarCom from "./components/NavbarCom";
import FooterComp from "./components/FooterComp";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// import { MaintenanceProvider } from "@/app/context/MaintenanceProvider";
import ContextProvider from "./context";
import { headers } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookies = (await headers()).get('cookie')

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-b from-gray-900 to-purple-900 text-white`}
      >
        <ContextProvider cookies={cookies}>
          <TranslationProvider>
            <ClientSessionProvider>
              {/* <MaintenanceProvider> */}
                <NavbarCom />
                {children}

                <FooterComp />
              {/* </MaintenanceProvider> */}
            </ClientSessionProvider>
          </TranslationProvider>
          <ToastContainer />
        </ContextProvider>
      </body>
    </html>
  );
}
